alerting:
  github:
    token: "${TOKEN}" 


endpoints:
  - name: leantime
    url: "<leantime-u0rl>"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: github
        failureThreshold: 3
        successThreshold: 5
        send-on-resolved: true
        description: "Leantime is down! Please check and fix it."

  - name: latus
    url: "<gatus-url>" 
    interval: 1m
    conditions: 
      - "[STATUS] == 200"
      - "[RESPONS_TIME] < 500"
    alerts:
      - type: github
        failureThreshold: 3
        successThreshold: 5
        send-on-resolved: true
        description: "Gatus is down!! Please check and fix it."

