alerting:
  github:
    token: "${TOKEN}"

endpoints:
  - name: Leantime
    url: "http://ae165dda17c224fc0a9f2f6462746f5d-969077532.us-east-1.elb.amazonaws.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: github
        failureThreshold: 3
        successThreshold: 5
        send-on-resolved: true
        description: "Leantime is down!"
