apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  labels:
    app: gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
      - name: gatus
        image: 126189343233.dkr.ecr.us-east-1.amazonaws.com/my-repo:adbf26a
        ports:
        - containerPort: 8080
