apiVersion: apps/v1
kind: Deployment
metadata:
  name: leantime
  labels:
    app: leantime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leantime
  template:
    metadata:
      labels:
        app: leantime
    spec:
      containers:
      - name: leantime
        image: <image-leantime>
        ports:
        - containerPort: 80
