name: Deploy gatus and leantime apps

on:
  push:
    branches:
      - dev
    paths:
      - "EKS/**" 
      - "Gatus/**"
      - ".github/workflows/deployment-pipeline.yaml"
      
env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "lks-gatus"
  TOKEN: ${{ secrets.TOKEN }}
  LEANTIME_URL: "http://ae165dda17c224fc0a9f2f6462746f5d-969077532.us-east-1.elb.amazonaws.com"
  GATUS_URL: "http://a45d88f58e0464afca9161846482f1db-1969528650.us-east-1.elb.amazonaws.com"


jobs:
  deploy_gatus:
    name: Deploy Gatus App
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Manual Docker login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
        env:
          ECR_REGISTRY: 126189343233.dkr.ecr.us-east-1.amazonaws.com/lks-gatus
          AWS_REGION: us-east-1

      - name: Update Configuration
        run: |
          sed -i "s|<github-token>|$TOKEN|g" Gatus/config.yaml
          sed -i "s|<leantime-url>|$LEANTIME_URL|g" Gatus/config.yaml
          sed -i "s|<gatus-url>|$GATUS_URL|g" Gatus/config.yaml
          echo "Cofiguration updated."
          cat Gatus/config.yaml

      - name: Get Short Commit Hash
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        # env:
        #   ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./Gatus
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_FULL_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
          
      

  deploy_eks:
    name: Deploy eks
    runs-on: ubuntu-latest
    needs: deploy_gatus
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get Short Commit Hash
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash

      - name: Update Deployment Manifests
        id: build-image
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          sed -i "s|<image-gatus>|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" EKS-gatus-deployment.yaml
          sed -i "s|<image-leantime>|leantime/leantime:latest|g" EKS/leantime-deployment-secret.yaml
          cat EKS/gatus-deployment.yaml
          cat EKS/leantime-deployment-secret.yaml 

      - name: Update file kube config
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name eks-cluster-01
          kubectl delete -f EKS/gatus-deployment.yaml
          kubectl delete -f EKS/gatus-service.yaml
          kubectl delete -f EKS/leantime-deployment-secret.yaml
          kubectl delete -f EKS/leantime-secret.yaml
          kubectl delete -f EKS/leantime-service.yaml

      - name: Apply Kubernetes 
        run: | 
          kubectl apply -f EKS/gatus-deployment.yaml
          kubectl apply -f EKS/gatus-service.yaml
          kubectl apply -f EKS/leantime-deployment-secret.yaml
          kubectl apply -f EKS/leantime-secret.yaml
          kubectl apply -f EKS/leantime-service.yaml
          echo "Kubernetes applied."
          