name: Deploy gatus and leantime apps

on:
  push:
    branches:
      - dev
    paths:
      - "EKS/**" 
      - "Gatus/**"
      - ".github/workflows/deployment-pipeline.yaml"
      
env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "lks-gatus"
  TOKEN: ${{ secrets.TOKEN }}
  #LEANTIME_URL: "${{ ALB_ENDPOINT }}"
  # GATUS_URL: ""


jobs:
  deploy_gatus:
    name: Deploy Gatus App
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update Configuration
        run: |
          sed -i "s|<github-token>|$TOKEN|g" Gatus/config.yaml
          sed -i "s|<leantime-url>|$LEANTIME_URL|g" EKS/leantime-deployment-secret.yaml
          sed -i "s|<gatus-url>|$GATUS_URL|g" Gatus/config.yaml
          echo "Cofiguration updated."
          cat Gatus/config.yaml

      - name: Get Short Commit Hash
        id: set-tag
        run: echo "image_tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        outputs:
          image_tag: ${{ steps.set-tag.outputs.image_tag }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./Gatus
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_FULL_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
          
      

  deploy_eks:
    name: Deploy eks
    runs-on: ubuntu-latest
    needs: deploy_gatus
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update Deployment Manifests
        run: |
          sed -i "s|<image-gatus>|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" EKS/gatus-deployment.yaml
          sed -i "s|<image-leantime>|leantime/leantime:latest|g" EKS/leantime-deployment-secret.yaml
          echo "Deployment manifests updated."
          cat EKS/gatus-deployment.yaml
          cat EKS/leantime-deployment-secret.yaml  

      - env:
        MAGE_TAG: ${{ needs.deploy_gatus.outputs.image_tag }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_FULL_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Apply Kubernetes 
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name eks-cluster-01
          kubectl apply -f EKS/gatus-deployment.yaml
          kubectl apply -f EKS/gatus-service.yaml
          kubectl apply -f EKS/leantime-deployment-secret.yaml
          kubectl apply -f EKS/leantime-secret.yaml
          kubectl apply -f EKS/leantime-service.yaml
          echo "Kubernetes applied."
          